;Constants
;=========

SCREEN_ADDRESS = 		$4000
SCREEN_WIDTH = 			256
SCREEN_HEIGHT =			128
CHAR_WIDTH = 			16
CHAR_HEIGHT = 			16
CHAR_SCREEN_WIDTH = 	16
CHAR_SCREEN_HEIGHT = 	16

;Object types
OBJ_FLOAT = 1
OBJ_STR = 2
OBJ_HEX = 3

;Input buffer
BUFF_SIZE =				64
WORD_MAX_SIZE =			18	;1.23456789012e-999
INPUT_Y =				(SCREEN_ADDRESS / 256)+CHAR_HEIGHT*6+12

;Key constants
KEY_BACKSPACE = 		8
KEY_ENTER = 			13
KEY_ESCAPE =			27

;Input modes for word finder
MODE_NONE = 			0
MODE_STRING =			1

;Error codes
ERROR_NONE =			0
ERROR_WORD_TOO_LONG =	1
