
//Taken from Python key label script...
BUTTON_COUNT_X=5;
BUTTON_COUNT_Y=8;

BUTTON_WIDTH=120;
BUTTON_HEIGHT=80;
BUTTON_GAP_HORZ=32.4;
BUTTON_GAP_VERT=72.4;
BUTTON_BORDER_HORZ=20;
BUTTON_BORDER_VERT=20;

//Added for test
BUTTON_DEPTH=20;
KEYPAD_BORDER_HORZ=BUTTON_GAP_HORZ;
KEYPAD_WIDTH=BUTTON_COUNT_X*(BUTTON_WIDTH+BUTTON_GAP_HORZ)+BUTTON_GAP_HORZ+KEYPAD_BORDER_HORZ*2;
KEYPAD_HEIGHT=BUTTON_HEIGHT+2*BUTTON_GAP_VERT;

//Mold box
MOLD_GAP_HORZ=100;
MOLD_GAP_VERT=100;
MOLD_FLOOR_THICKNESS=20;
MOLD_WALL_HEIGHT=80;
MOLD_WALL_THICKNESS=30;

module keypad_row()
{
  difference()
  {
    //keypad layer
    cube([KEYPAD_WIDTH,KEYPAD_HEIGHT,BUTTON_DEPTH]);

    //key holes
    for (i=[0:BUTTON_COUNT_X-1])
    {
      translate([BUTTON_GAP_HORZ+i*(BUTTON_WIDTH+BUTTON_GAP_HORZ)+KEYPAD_BORDER_HORZ,BUTTON_GAP_VERT,-1])
      cube([BUTTON_WIDTH,BUTTON_HEIGHT,BUTTON_DEPTH+2]);
    }
  }
}

module mold()
{
  difference()
  {
    //outside block
    cube([KEYPAD_WIDTH+MOLD_GAP_HORZ*2+MOLD_WALL_THICKNESS*2,
    KEYPAD_HEIGHT+MOLD_GAP_VERT*2+MOLD_WALL_THICKNESS*2,
    MOLD_FLOOR_THICKNESS+MOLD_WALL_HEIGHT]);
    
    //hollow out inside
    translate([MOLD_WALL_THICKNESS,MOLD_WALL_THICKNESS,
      MOLD_FLOOR_THICKNESS])
    cube([KEYPAD_WIDTH+MOLD_GAP_HORZ*2,
    KEYPAD_HEIGHT+MOLD_GAP_VERT*2,
    MOLD_WALL_HEIGHT+1]);
  }
}

/*
scale([0.1,0.1,0.1])
union()
{
  mold();
  translate([MOLD_GAP_HORZ+MOLD_WALL_THICKNESS,MOLD_GAP_VERT+MOLD_WALL_THICKNESS,MOLD_FLOOR_THICKNESS])
  keypad_row();
}
*/

INNER_WIDTH=KEYPAD_WIDTH+MOLD_GAP_HORZ*2;
INNER_LENGTH=KEYPAD_HEIGHT+MOLD_GAP_VERT*2;
INNER_HEIGHT=MOLD_WALL_HEIGHT;

module outer()
{
  union()
  {
  difference()
  {
    //outside block (new for outer)
    cube([INNER_WIDTH+4*MOLD_WALL_THICKNESS,
    INNER_LENGTH+4*MOLD_WALL_THICKNESS,
    2*INNER_HEIGHT+MOLD_FLOOR_THICKNESS]);
   
    //outside block of original mold
    //(inside block of outer)
    translate([MOLD_WALL_THICKNESS,MOLD_WALL_THICKNESS, MOLD_FLOOR_THICKNESS])
    cube([INNER_WIDTH+2*MOLD_WALL_THICKNESS,INNER_LENGTH+2*MOLD_WALL_THICKNESS,2*INNER_HEIGHT+1]);
  }
  
  //outline of original mold
  translate([2*MOLD_WALL_THICKNESS,2*MOLD_WALL_THICKNESS, MOLD_FLOOR_THICKNESS])
  cube([INNER_WIDTH,INNER_LENGTH,INNER_HEIGHT]);
  }
}

scale([0.1,0.1,0.1])
outer();

