	VM_DEBUG_WORDS_LEN: FCB 10
	VM_DEBUG_WORDS:
	FCB "VM>      ",0
	FCB "!        ",0
	FCB "DUP      ",0
	FCB "OVER     ",0
	FCB "I        ",0
	FCB "1+       ",0
	FCB "RSHIFT   ",0
	FCB "A        ",0
	FCB "+        ",0
	FCB "-        ",0
	FCB "LSHIFT   ",0
	FCB "C!       ",0
	FCB "DO       ",0
	FCB "JSR      ",0
	FCB "DROP     ",0
	FCB "HALT     ",0
	FCB "DEBUG    ",0
	FCB "SWAP     ",0
	FCB "@        ",0
	FCB "SELECT   ",0
	FCB "AND      ",0
	FCB "XOR      ",0
	FCB "C@       ",0
	FCB "EXEC     ",0
	FCB "VM...    ",0
	FCB "<        ",0
	FCB "=        ",0
	FCB "FDROP    ",0
	FCB "FNEW     ",0
	FCB "FSP      ",0
	FCB "FTOS     ",0
	FCB "PUSH_RES ",0
	FCB "PUSH_BYTE",0
	FCB "LOOP     ",0
	FCB "IF       ",0
	FCB "WHILE    ",0
	FCB "ELSE     ",0
